name: Test PR
on: pull_request

permissions:
  contents: read
  packages: write

jobs:
  check_lockfiles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pip install poetry
      - name: Check lockfiles
        run: poetry check --lock
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # lint
      - uses: chartboost/ruff-action@v1
      # check formatting
      - uses: chartboost/ruff-action@v1
        with:
          args: format --check
  create_image:
    name: Create docker image
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pip install poetry
      - name: Export poetry to requirements.txt
        run: poetry export -o requirements.txt
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/itmo-mlops-2024/backend:latest
